accounts/urls.py
from .views import SignupView
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('signup/',SignupView.as_view(),name = 'signup'),
]

chat/urls.py
from django.urls import path
from .views import chat_view
app_name = 'chat'
urlpatterns = [
    path('',chat_view, name='chat')
]

feed/urls.py
from django.urls import path,include
from .views import feedview
app_name = 'feed'
urlpatterns = [
    path('',feedview,name='feed'),
] 

home/urls.py
from django.urls import path,include
from .views import HomeTemplateView, NetworkTemplateView 
app_name = 'home'
urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('network/', NetworkTemplateView.as_view(), name='network')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import LoginAuthView,CustomLogoutView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/login/',LoginAuthView.as_view(), name='login'),
    path('accounts/logout/',CustomLogoutView.as_view(), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('feed/', include('feed.urls')),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls'))
]

posts/urls.py
from django.urls import path
from .views import (
    create_posts_view,
    detail_posts_view,
    update_posts_view,
    delete_posts_view,
    my_postsview,
    post_category_view,
    post_like_view,
)

app_name = 'posts'

urlpatterns = [
    path('create/', create_posts_view, name='create_posts'),
    path('update/<int:id>/', update_posts_view, name='update_post'),
    path('detail/<int:id>', detail_posts_view, name='detail_post'),
    path('delete/<int:id>', delete_posts_view, name='delete_post'),
    path('my-posts/', my_postsview, name='my_posts'),
    path('category/<str:cats>/', post_category_view, name='post_category'),
    path('post_like/<int:id>',post_like_view, name='post_like'),
] 

feed/models.py
from django.db import models

# Create your models here.

feed/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from posts.models import Post,Category
# Create your views here.

@login_required
def feedview(request):
    context = {}
    list_posts = Post.objects.all()
    category_item = Category.objects.all()
    context['list_posts'] = list_posts
    context['category_item'] = category_item
    current_user = request.user
    context['current_user'] = current_user
    
    return render(request, 'feed/feed.html', context)

feed/templates/feed/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PyAcademia | Home</title>
    <link rel="stylesheet" href="{% static 'feed/css/base.css' %}">
    {% block extra_css %}
    {% endblock %}
</head>
<body>
           
     <header>
        <nav>
            <div class="logo">
                <a href="">
                    {{request.user}}
                    <span class="first-word">Py</span> Academia
                </a>
            </div>
            <div class="menu">
                 <a href="{% url 'home:home'%}">Home</a> 
                 <a href="#">Network</a> 
                 <a href="{% url 'feed:feed'%}">Feed</a> 
                 <a href="{% url 'chat:chat'%}">Messaging</a>
                

                 
            </div>
            <div class="signup" >
                {% if user.is_authenticated %}
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Log Out</button>
                  </form>
                {% else %}
                <form action="{% url 'accounts:signup' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Register</button>
                  </form>
                {% endif %}
            </div>
        </nav>
    </header>

    
    {% block content %}
    
    {% endblock %}
</body>
</html>




<!-- {% if user.is_authenticated %}
        <a href="{% url 'chat:chat'%}">messaging</a>
            Hi {{ user.username }}! ||| <a href="{% url 'posts:create_posts' %}">Create Post</a>
             <a href="{% url 'posts:my_posts'%}">My Posts</a>
        {% endif %}
        <hr>
        {% for item in category_item %}
       <a href="{% url 'posts:post_category' item %}"> {{item}}</a> ||
        {% endfor %}
        <hr> -->

feed/templates/feed/create_post.html
{% extends 'feed/base.html' %} 

{% block content %}
    <h1>{{request.user}} is creating post</h1>
    <form action="{% url 'posts:create_posts' %}" method="post">
        {% csrf_token %}
        <label for="">{{form.title.label_tag}}</label>
        {{form.title}}

        <label for="">{{form.content.label_tag}}</label>
        {{form.content}}

        <label for="">{{form.category.label_tag}}</label>
        {{form.category}}
        <label for="">{{form.visibility.label_tag}}</label>
        {{form.visibility}}
        <button type="submit">Create Post</button>

    </form>
{% endblock %}

feed/templates/feed/feed.html
{% extends 'feed/base.html' %} 
<!-- {% load static %} -->
{% block extra_css %}
<link rel="stylesheet" href="{% static 'feed/css/feed.css' %}">
{% endblock %}

{% block content %}
<!-- {% if user.is_authenticated %}
        <a href="{% url 'chat:chat' %}">messaging</a>
            Hi {{ user.username }}! ||| <a href="{% url 'posts:create_posts' %}">Create Post</a>
             <a href="{% url 'posts:my_posts'%}">My Posts</a>
             <hr>
        {% endif %} -->

  <section class="parent-section">
    {% if user.is_authenticated %}
    <a href="{% url 'posts:create_posts' %}">Create Post</a>
        {% for post in list_posts %}
          <div class="post-inner-card">
            <div class="post-user">
              <p>  {{post.author}}</p> 
              <p>{{post.created_date}}</p>
            </div>
            <div class="post-body">
              <a  class="title" href="{% url 'posts:detail_post' post.id %}">{{post.title}} </a>
              
              <a class="category" href="{% url 'posts:post_category' post.category %}">{{post.category}}</a>
              <form action="{% url 'posts:post_like' post.id %}" method="post">
                {% csrf_token %}
                <p>total likes are {{ post.likes.count }}</p>
                <button type="submit" >
                  {% if request.user in post.likes.all %}
                  Unlike
              {% else %}
                  Like
              {% endif %}</button>
              </form>
            </div>
          </div>
          
        {% endfor %}   
      
    {% endif %}
  </section>
{% endblock %}

feed/templates/feed/my_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for post in my_posts %}
        <a href="{% url 'posts:detail_post' post.id %}">{{post.title}}</a>
     <hr>

        {% endfor %}
</body>
</html>

feed/templates/feed/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>post detail</title>
</head>
<body>
    
    {{post_to_update.title}} <br>
    {{post_to_update.content}} <br>
    {{post_to_update.created_date}} <br>
    {{post_to_update.visibilpost_to_update}}
    
    {% if request.user == post_to_update.author  %}
    <a href="{% url 'posts:update_post' post_to_update.id %}">update</a> <br>
    <a href="{% url 'posts:delete_post' post_to_update.id %}">delete</a>
        
      <hr>

    {% endif %}
</body>
</html>

feed/templates/feed/posts_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{cats}}

{% if post_categories %}
{% for cat_post in post_categories %}
    <a href="{% url 'posts:detail_post' cat_post.id %}">{{cat_post.title}} {{cat_post.created_date}}  {{cat_post.author}} {{cat_post.category}}</a> 
    &nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;<a href="">like</a> 
    <hr>
{% endfor %}

{% else %}

<h1>{{cats}} related posts not available</h1>
{% endif %}
</body>
</html>

feed/templates/feed/update_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        {% if request.user == post_to_update.author  %}
    <form action="{% url 'posts:update_post' post_to_update.id %}" method="post" >
        {% csrf_token %}
        {{form.as_p}}
     <button type="submit">Update Post</button>
    </form>
        {% endif %}
        {% endif %}
    
</body>
</html>